### ISSUE TITLE
Importing FreeBSD changes regarding GNU software (among other things)

### ISSUE THREAD

**Issue by planetbrian** [MidnightBSD/src#160]
Good morning,

Firstly, I would like to thank you for creating this amazing piece of software :) Keep doing what you do!

As this project occasionally imports changes from FreeBSD, I was wondering if there was any desire to rebase the changes from [their src-tree's gnu directory](https://github.com/freebsd/freebsd-src/tree/main/gnu). I understand that ridding all GPL-licensed code from base is a FreeBSD goal, but it would be interesting to know how those changes will interact with MidnightBSD. Beyond this, would it benefit MidnightBSD to grab code from the other directories (such as kerberos5)? Perhaps this could be a major release feature down the road?

**Comment by laffer1** [comment]
From a project perspective, we do prefer BSD or MIT licensed code over GPL.  However, we don't have a strict rule to rid ourselves of GPL licensed code in base.  If there is a "better" licensed package that works similarly, we would consider it. 

We did migrate some things in current / 3.x branches in the last few months to non GPL licensed code. 

Current is roughly in sync with FreeBSD 12-stable (~july 2022)

At the moment, we're focused on getting mports in shape for the 3.x release.  That's mostly blocked on LLVM port issues at the moment. We're also trying to update some third party software in base that hasn't been updated in awhile or has security issues like less, openssl, sqlite3, subversion, etc.  The vendor branches are a bit of a mess after the git conversion and we're slowly cleaning that up.
