### ISSUE TITLE
Compile glib schemas

### ISSUE THREAD

**Issue by ilius** [MidnightBSD/src#86]
Some Gtk applications crash, unless user runs this command manually:

    sudo glib-compile-schemas /usr/share/glib-2.0/schemas/

which creates the file `/usr/local/share/glib-2.0/schemas/gschemas.compiled`.
This should be done during installation.

**Comment by laffer1** [comment]
Do you have examples for this? 
The plist should get a @postexec with glib-compile-schemas applied.

**Comment by ilius** [comment]
What kind of example?

That file did not exist after installation.
The crashing was fixed right after I ran above command.
Happened with 2 applications for me, one in C (mousepad or leafpad) and one Python3 (my own).

**Comment by laffer1** [comment]
For mousepad, glib-compile-schemas is getting installed with glib20 and the PLIST does contain the postexec line above.  Running deinstall reinstall on MidnightBSD 2.1.2, it seems to update the gschemas.compiled file.   glib20 is showing up as a build and run depends too. 

Wondering if there is some path issue on a fresh install (csh rehash)   We may want to do %D/bin/glib-compile-schemas

**Comment by laffer1** [comment]
I've modified the script to use an explicit path.  There's also a change to mport to support a @glib-schemas annotation in the PLIST going forward which uses an explicit path for this.

**Comment by ilius** [comment]
Sorry, I deleted the virtual machine a while back.
I can test install MidnightBSD again later and test.
How can I upgrade mports?

**Comment by laffer1** [comment]
Rather than installing mports during install, you can get it via portsnap 

portsnap fetch extract

Then you can portsnap fetch update or run make update in /usr/mports

You can also check it out from GitHub directly using git or svnlite. The former will have to be installed with mport install git


Lucas Holt

**Comment by ilius** [comment]
Yes, the problem seems to be resolved.
Tested with both mousepad and python3.8 gobject.
