### ISSUE TITLE
Create Python symbolic links

### ISSUE THREAD

**Issue by ilius** [MidnightBSD/src#87]
When you install Python 3.8 for example, all these commands should be available: `python3.8`, `python3`, `python`.

These commands will fix the issue

	ln -s /usr/local/bin/python3.8 /usr/local/bin/python3
	ln -s /usr/local/bin/python3 /usr/local/bin/python

But user shouldn't have to do this manually.
They are created on any Linux distribution.

**Comment by laffer1** [comment]
They are available.  
mport install python3
