### ISSUE TITLE
Package py38-psutil does not work

### ISSUE THREAD

**Issue by ilius** [MidnightBSD/src#90]
Package `py38-psutil` does not work at all.
Steps to reproduce:

    mport install py38-psutil
    python3 -c 'import psutil'

The error:
![MidnightBSD-2 1 1-py38-psutil](https://user-images.githubusercontent.com/197648/142646193-299b4167-6a41-4458-b9f3-d4e0fbdc4afd.png)

This PR https://github.com/giampaolo/psutil/pull/1996 fixes the issue, but the fix is not in any tag yet.
If you clone the repo and run `sudo python3 setup.py install`, it should work.

You can either wait for a tag, or update to the latest code from Github.

**Comment by laffer1** [comment]
Note it would be better to put mports related tickets on the mports github rather than src. 

I've updated the port to include your patch and submitted a new patch for the setup.py although that isn't required.  
https://github.com/giampaolo/psutil/pull/2019

**Comment by ilius** [comment]
Yeah I was doubtful about that because I didn't see any open/closed issues in mports!

**Comment by laffer1** [comment]
We usually use jira instead, but I'm forgiving of github because some folks don't like signing up for jira. 
https://bugreport.midnightbsd.org/

**Comment by laffer1** [comment]
Updated the sysutils/py-psutil port with a similar patch locally for now.
